# Site settings
title: AdAway
email: info@adaway.org
description: > # this means to ignore newlines until "baseurl:"
  AdAway is an open source ad blocker for Android using the hosts file.
baseurl: ""
url: "https://adaway.org"
github_username: AdAway

# Build settings
markdown: kramdown